#define THMEDIA_IR_PWM1 14

#define THMEDIA_IR_PWM2 27

#define THMEDIA_IR_PWM3 26

#define THMEDIA_IR_PWM4 25

#define THMEDIA_IR_PWM5 33

#define THMEDIA_IR_PWM6 32

#define THMEDIA_IR_PWM7 15

#define THMEDIA_IR_PWM8 2

#define THMEDIA_IR_LED_ARRAY {THMEDIA_RF, THMEDIA_IR_PWM1, THMEDIA_IR_PWM2, THMEDIA_IR_PWM3, THMEDIA_IR_PWM4, THMEDIA_IR_PWM5, THMEDIA_IR_PWM6, THMEDIA_IR_PWM7, THMEDIA_IR_PWM8}

#define THMEDIA_RF 4

#define thmediaIrRx 21

#define thmediaRfRx 12

void thmedia_setup();
