#define THMEDIA_IR_PWM1 -1
#define THMEDIA_uC_IR_CTRL1 -1

#define THMEDIA_IR_PWM2 2
#define THMEDIA_uC_IR_CTRL2 15

#define THMEDIA_IR_PWM3 4
#define THMEDIA_uC_IR_CTRL3 0

#define THMEDIA_IR_PWM4 12
#define THMEDIA_uC_IR_CTRL4 13

#define THMEDIA_IR_PWM5 27
#define THMEDIA_uC_IR_CTRL5 14

#define THMEDIA_IR_PWM6 35
#define THMEDIA_uC_IR_CTRL6 34

#define THMEDIA_IR_PWM7 33
#define THMEDIA_uC_IR_CTRL7 32

#define THMEDIA_IR_PWM8 26
#define THMEDIA_uC_IR_CTRL8 25

#define THMEDIA_IR_LED_ARRAY {THMEDIA_IR_PWM1, THMEDIA_IR_PWM2, THMEDIA_IR_PWM3, THMEDIA_IR_PWM4, THMEDIA_IR_PWM5, THMEDIA_IR_PWM6, THMEDIA_IR_PWM7, THMEDIA_IR_PWM8}

void thmedia_setup();
